name: swipl
base: core18
adopt-info: swi-prolog
license: 'BSD-2-Clause'
summary: ISO/Edinburgh-style Prolog implementation
description: |
  SWI-Prolog is a fast and powerful ISO/Edinburgh-style Prolog compiler with a
  rich set of built-in predicates. It offers a fast, robust and small
  environment which enables substantial applications to be developed with it.
  .
  SWI-Prolog additionally offers:
  .
  * A powerful module system
  * Garbage collection
  * Unicode character set handling
  * Unbounted integer and rational number arithmetic
  * Multithreading support
  * A powerful C/C++ interface
  * GNU Readline interface
  .

apps:
  swipl:
    command: desktop-launch $SNAP/usr/local/bin/swipl
  swipl-win:
    command: desktop-launch $SNAP/usr/local/bin/swipl-win

plugs:
  home:
  network:
  x11:
  desktop:
  desktop-legacy:
  removable-media:
  opengl:
  audio-playback:
  audio-record:

grade: stable
confinement: strict

environment:
  LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/local/lib/swipl/lib/$(uname -m)-linux"

parts:
  swi-prolog:
    source: .
    # source-type: git
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(cat VERSION)"
    override-build: |
      # Custom build process to enable PGO build
      mkdir -p $SNAPCRAFT_PART_SRC/build
      cd $SNAPCRAFT_PART_SRC/build
      cmake -DCMAKE_BUILD_TYPE=Release -DSWIPL_PACKAGES_JAVA=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -G Ninja ..
      ../scripts/pgo-compile.sh
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
    stage-packages: 
      - ca-certificates
      - libarchive13
      - libdb5.3
      - libedit2
      - libfontconfig1
      - libglu1-mesa
      - libgmp10
      - libjpeg8
      - libmariadbclient18
      - libossp-uuid16
      - libpcre3
      - libserd-0-0
      - libssl1.1
      - libx11-6
      - libxft2
      - libxpm4
      - libxt6
      - odbc-postgresql
      - tdsodbc
      - unixodbc
      - libdouble-conversion1
      - libgraphite2-3
      - libharfbuzz0b
      - libqt5core5a
      - libqt5widgets5
    build-packages:
      - libarchive-dev
      - libdb-dev
      - libedit-dev
      - libgeos++-dev
      - libgmp-dev
      - libice-dev
      - libjpeg-dev
      - libossp-uuid-dev
      - libpcre3-dev
      - libraptor2-dev
      - libreadline-dev
      - libserd-dev
      - libsqlite3-dev
      - libssl-dev
      - libxext-dev
      - libxft-dev
      - libxinerama-dev
      - libxpm-dev
      - libxt-dev
      - ninja-build
      - unixodbc-dev
      - zlib1g-dev
      - libyaml-dev
      - qtbase5-dev

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all

  # glib-only:
  #   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  #   source-subdir: glib-only
  #   plugin: make
  #   build-packages:
  #     - libglib2.0-dev
  #   stage-packages:
  #     - libglib2.0-bin

