name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: MinGW install
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install wine-stable wine-stable:i386 wine-binfmt mingw-w64 winetricks wget xvfb
    - name: Install wine dependencies
      run: |
        xvfb-run winetricks --unattended vcrun2017
        wget -q -O nsis.exe https://sourceforge.net/projects/nsis/files/NSIS%203/3.04/nsis-3.04-setup.exe/download
        wine nsis.exe /S
    - name: Build swipl
      run: |
        cp README.mingw ..
        cd ..
        . README.mingw win64
        #download_prerequisites
        #build_all
        build_release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
